/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_alphadog_mytestapplication_jni_HelloJni */

#ifndef _Included_com_example_alphadog_mytestapplication_jni_HelloJni
#define _Included_com_example_alphadog_mytestapplication_jni_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_alphadog_mytestapplication_jni_HelloJni
 * Method:    helloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_alphadog_mytestapplication_jni_HelloJni_helloJni
  (JNIEnv *, jclass);

/*
 * Class:     com_example_alphadog_mytestapplication_jni_HelloJni
 * Method:    addJni
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_alphadog_mytestapplication_jni_HelloJni_addJni
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
